name: weather_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bezier_chart: ^1.0.17+1
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1
  sensors: ^0.4.2+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: PTSerif
      fonts:
        - asset: assets/fonts/PTSerif/PTSerif-Regular.ttf
        - asset: assets/fonts/PTSerif/PTSerif-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
